# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MrBogomips' Bits and Bytes
subtitle: A tech blog with a personal touch
name: 
repository: MrBogomips/MrBogomips.github.io
url: https://mrbogomips.net/
email:
description: >- # this means to ignore newlines until "baseurl:"
  A blog exploring the challenges of EAP, DDD and .NET development, 
  while gaining personal insights from a seasoned architect and IT manager.
twitter_username: mrbogomips
github_username: MrBogomips
minimal_mistakes_skin    : "air" # "deafult", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-EK7TW9HX52"
    anonymize_ip: false
after_footer_scripts:
  - https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
  - assets/js/clipboardrouge.js



# Head scripts
# head_scripts:

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
breadcrumbs: true

# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Rome

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Giovanni Costagliola"
  avatar : "/assets/images/me.jpg"
  bio    : >-
    Passionate technologist and seasoned professional in enterprise application development, 
    with expertise in business analysis, software and system architecture design,
    team leading and project management.
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MrBogomips"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mrbogomips"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/giovannicostagliola/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MrBogomips"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mrbogomips"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/giovannicostagliola/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      show_date: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: "_projects"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  projects:
    output: true
    permalink: /:collection/:path

comments:
  provider: "disqus"
  disqus:
    shortname: "mrbogomips"
